sudo: required

services:
  - docker

language: node_js
node_js:
  - "9.10.0"

before_install:
  - docker build -t test -f tests/Dockerfile .

script:
  - docker run --rm -v $PWD/src:/app/src -v $PWD/tests:/app/tests test sh -lc 'yarn test'

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"